version: "3"
services:
  database:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  backend:
    build: ./backend
    ports:
      - 4000:4000
    depends_on:
      - database
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
