version: "3"

services:
  database:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  backend:
    build: ./backend
    volumes:
      - ./backend:/myapp
    ports:
      - 4000:4000
    depends_on:
      - database

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/myapp
      - node_modules:/myapp/node_modules
      - yarn_cache:/yarn
    ports:
      - 3000:3000

volumes:
  postgres:
  node_modules:
  yarn_cache:
