# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Post.create([
  { title: 'Aliquam sit amet enim blandit, suscipit quam ac, convallis felis.', body: 'Praesent eget nisi eu sem sodales iaculis et ut mauris. Nulla congue massa eget varius accumsan. Donec at suscipit ipsum. Sed ultrices, orci et vestibulum eleifend, odio ligula tempor diam, eu pharetra sapien justo a massa. Etiam viverra cursus volutpat. Curabitur eu dapibus metus. In purus odio, bibendum nec hendrerit in, lacinia ullamcorper tellus. Nullam consectetur, ipsum in sodales commodo, nulla neque elementum dui, eu varius risus ligula a nisl.' },
  { title: 'Etiam quis felis quis lectus ullamcorper vestibulum id quis mauris.', body: 'Pellentesque vestibulum ultricies velit id ultricies. Donec sagittis malesuada nisl in feugiat. Morbi justo dolor, blandit a leo non, tincidunt pulvinar ex. Duis dapibus finibus iaculis. Ut varius ligula quis pulvinar ullamcorper. Fusce auctor gravida elit. In pharetra orci eu turpis finibus, non gravida augue pharetra. Donec at felis nisi. Curabitur semper dictum mattis. Fusce accumsan suscipit tincidunt. Nunc in lacinia risus. Aliquam lobortis, nunc ac vehicula efficitur, justo nulla interdum ligula, sed mollis massa massa vel augue. Mauris venenatis volutpat tortor, vitae sodales magna.' },
  { title: 'Ut non eros sed nulla molestie bibendum sit amet vel felis.', body: 'Nulla vulputate tincidunt sem a maximus. Integer posuere vestibulum semper. Sed eget mauris vitae ligula vestibulum imperdiet sit amet sit amet velit. Fusce gravida malesuada ante, et pharetra lorem aliquet vel. Vivamus augue orci, volutpat quis diam sed, euismod interdum dolor. Ut dictum viverra ante, a accumsan ex malesuada et. Suspendisse posuere molestie nisl ac mollis. Fusce condimentum, dolor a pulvinar euismod, mi lectus euismod mi, in pharetra dui justo ac massa. Donec mattis lectus a finibus lacinia. Maecenas et pharetra nibh. Etiam pretium dapibus iaculis. Suspendisse sit amet quam tempor, egestas risus nec, vehicula nisi. Fusce sed sagittis augue. Donec vel eleifend ex. Fusce convallis, nunc ut placerat malesuada, eros turpis aliquet felis, at imperdiet ex odio et est.' },
  { title: 'In elementum velit molestie, tristique neque ac, convallis lorem.', body: 'Mauris erat tortor, commodo at sapien a, mollis bibendum nunc. Morbi malesuada id libero eu venenatis. Aenean faucibus orci vitae dolor aliquam, non auctor erat tempus. Phasellus maximus mauris eu augue finibus, eu semper lorem bibendum. Sed vulputate diam congue ex euismod, sit amet feugiat tortor placerat. Cras id semper orci, vel bibendum sem. Sed dui erat, euismod sit amet tristique id, convallis quis dolor.' },
  { title: 'Nullam condimentum diam id sem ultricies, aliquam gravida enim tristique.', body: 'Integer ornare turpis vitae mauris congue tempus. Vestibulum quis nisl suscipit, porta mi sit amet, congue turpis. Proin elit est, accumsan id gravida quis, fringilla sed est. Sed vel nulla vel mi elementum tempus. Quisque elementum arcu vitae nisl eleifend, eget pharetra dolor posuere. Maecenas fermentum ante augue, sit amet tristique magna ullamcorper eget. Praesent nisi massa, volutpat sit amet vehicula at, malesuada commodo magna. Phasellus et suscipit nisl. Vivamus laoreet sit amet augue sed varius. Nulla ut urna vitae ex porta efficitur sed in ipsum. Nulla et porttitor elit. Mauris dignissim eros sit amet tristique condimentum. Donec id quam eros. Phasellus gravida eu nulla vitae auctor. Cras finibus at est nec aliquet.' },
])